### PR TITLE
Composer-playground fix scrollbar height issue (#1503)

### PR DESCRIPTION
**Pull request by prasoc**
Fix for #1503 
A small change to use the browser's native scrollbar instead of the buggy CodeMirror "simple" scroll bar.

### CODE REVIEW

**Comment by prasoc** [comment]
Fixed.

**Comment by prasoc** [comment]
I'm not sure how the pull request gets into the state of "accepted". Is it automatic?

**Comment by caroline-church** [comment]
No someone has to approve the review, just need to check with the designers that it is ok

**Comment by prasoc** [comment]
OK that makes sense. Thanks for helping me through my first pull request

**Comment by winslet** [comment]
@caroline-church @prasoc based off of the below image (which I believe to be the latest code):

pasted image at 2017_07_10 07_23 pm

I would like to suggest a couple of small changes:

1) We add padding into the top/bottom to give the scroll bars some internal space in the div.
2) There is a hover state which increases the width of the scroll bars to what is suggested, the non hover stays the same as what is there currently (this might already be implemented - please ignore me if so!).
3) We make the colour of the scrollbars less transparent so they stand out more (trying to make sure these are accessible).

Thus it should have some behaviour similar to this:

image

@prasoc I realise this is your first PR so thank you in advance - as this is an important component used throughout the product we need to make sure we get it right 👍 

Any questions let me know 🎉

**Comment by prasoc** [comment]
There is an issue applying a padding-bottom to the CodeMirror .simple-scroll class because the height of the inner bar is calculated manually within the JS file, so it ends up off the edge of the container it's held within. This is problematic as we cannot alter the functionality of the "CodeMirror" NPM package to remedy this.

@winslet I have tried something different:

capture

This gets around the padding-bottom CodeMirror problem, what do you think? Thanks for being patient here, I am determined to get it right

**Comment by prasoc** [comment]
I will re-open this when I have pulled changes into the CodeMirror source that allows a padding on the simple scrollbar.

**Pull request closed without merging**
