### PR TITLE
Update developer-guide

### PR DESCRIPTION
**Pull request by aviralwal**
Problem: `npm test` failing

Correction: inside file package.json, the edit was suggested in doc to read jsdoc.conf which is not defined. It should be jsdoc.json instead.

### CODE REVIEW

**Comment by caroline-church** [comment]
@EdProsser can you review this please?

**Comment by sstone1** [comment]
@aviralwal please can you take care of the merge conflicts so we can pull this in?

**Comment by caroline-church** [comment]
@aviralwal I think you might have lost some of the changes you made. The changes now don't look like the original changes?

**Comment by aviralwal** [comment]
Sorry about that. Created the original changes i suggested.

**Comment by caroline-church** [comment]
@EdProsser Can you review this again please?

**Comment by EdProsser** [comment]
The docs have been updated since this PR was made, so rejecting this PR.

**Comment by aviralwal** [comment]
So should i close the pull request @EdProsser

**Comment by EdProsser** [comment]
I'll close it now, the changes that went in should suffice. :)

**Pull request closed without merging**
