### PR TITLE
Transaction generation

### PR DESCRIPTION
**Pull request by sngvahmed**
make the generation for transaction 

## Checklist
 - add generation for transaction generation 
 - i work in user story number [3136](https://github.com/hyperledger/composer/issues/3136)
 - i made generation for transaction and handle also if transaction have asset i generate the model inside this asset

## Issue/User story
i Work in user story [3136](https://github.com/hyperledger/composer/issues/3136)

### CODE REVIEW

**Comment by sngvahmed** [comment]
I solve the conflict with master and doc sign off

**Comment by bestbeforetoday** [comment]
@sngvahmed This pull request still looks to have merge conflicts with _master_, and is missing the DCO sign-off. The easiest way to solve the sign-off problem (since all commits must include correct sign-off text) might be to squash all of your commits to a single commit, and commit that with `git commit --signoff` to ensure the correct sign-off text is included in the commit message.

**Comment by dselman** [comment]
You might want to check this project out: https://github.com/uchibeke/composer-form

**Comment by davidkel** [comment]
Hi, the angular generator now has basic transaction support. So not sure this PR is now valid. If there are any improvements you wish to submit then please submit a new PR.
Closing due to not relevant now.

**Pull request closed without merging**
