### PR TITLE
ParticipantRegisty typo fix

### PR DESCRIPTION
**Pull request by saichaitanya88**
Please update ParticipantRegisty to ParticipantRegistry.

### CODE REVIEW

**Comment by saichaitanya88** [comment]
Not very familiar with the pull request process. If someone volunteers to make the proposed changes, this pull request can be scrapped. Automated checks do not seem to be passing.

**Comment by sstone1** [comment]
@saichaitanya88 there are two instances of `ParticipantRegisty` in `issue-identity.component.spec.ts`, you fixed the import but not the use of it below.

You also need to sign off your commits for the DCO (contributor agreement). This is the `-s` flag to `git commit`. Since you already have commits, you need to fix the commit messages in all of the existing commits. Try this:

```
git fetch upstream master
git rebase --signoff upstream/master
```

**Comment by saichaitanya88** [comment]
Tried to fetch upstream master. Seems that I don't have the necessary permissions. The change set contains the missing line. Please feel free to close this request if you're able to commit these changes. I can't seem to update the DCO retrospectively...

**Comment by sstone1** [comment]
@saichaitanya88 I've updated the commands with a `git remote add` command that should resolve your problem trying to fetch upstream master - can you try it again please?

**Comment by saichaitanya88** [comment]
Thanks for providing the git remote add command. I tried git push -f, but it results in a permission error. 

ERROR: Permission to hyperledger/composer.git denied to saichaitanya88.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights the repository exists.

- 
Do you mind if I create a separate pull request with the signoff? and we can probably close this one and avoid the hassle.

**Comment by sstone1** [comment]
@saichaitanya88 sure, please open a new pull request once you’ve resolved the DCO problems.

**Pull request closed without merging**
