### PR TITLE
Fix #2462

### LINKED ISSUE #2462: Missing dependency: figlet
Running 
`composer shell`

I get:

```
Starting shell...
/Users/will/.nvm/versions/node/v7.10.0/lib/node_modules/composer-cli/node_modules/yargs/yargs.js:1079
      else throw err
           ^

Error: Cannot find module 'figlet'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/will/.nvm/versions/node/v7.10.0/lib/node_modules/composer-cli/shell.js:21:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

Installing the missing dependency manually fixed the issue:
```
cd /Users/will/.nvm/versions/node/v7.10.0/lib/node_modules/composer-cli
npm i figlet
```

### PR DESCRIPTION
**Pull request by chevdor**
Fix #2462

### CODE REVIEW

**Comment by caroline-church** [comment]
@chevdor Can you fix the conflicts please?

**Comment by chevdor** [comment]
@caroline-church Anything I should/can do to make DCO happier?

**Comment by mbwhite** [comment]
@chevdor   To get DCO correct - you'll need to go back and check the commit messages to see what are missing the signed off string.  They all have to have one.

`git log` should show which ones are missing.. then the notes @ https://help.github.com/articles/changing-a-commit-message/#amending-older-or-multiple-commit-messages should let you sort it out.

**Comment by caroline-church** [comment]
@chevdor Can you please fix the DCO sign off on this pr please

**Comment by chevdor** [comment]
I´ll have a look as soon as I have time. Making DCO happy at that point requires more work than the fix itself...

**Comment by chevdor** [comment]
PR cleaned up and replaced by #2529

**Pull request closed without merging**
