### PR TITLE
Fix for optional values being added without overwriting previous entries (Issue 1816)

### PR DESCRIPTION
**Pull request by awjh-ibm**
#1816 

Fix to keep user's previously entered data for fields when the user ticks the optional data checkbox. Optional data is discarded when box is unticked to match possible solution 3 of the issue.

Work performed:
- Added function to go through the optional data JSON and existing data JSON and use values from existing data for the key of the optional data, including treating each key in sub objects individually.
- Wrote tests to test new function worked and that existing functions called it when needed.
- Manually verified functionality in local build of playground

### CODE REVIEW

**Comment by awjh-ibm** [comment]
Updated code to fix generate code issue

**Comment by caroline-church** [comment]
@awjh-ibm can you fix the conflicts please?

**Comment by caroline-church** [comment]
@awjh-ibm i'd expect this to work for non optional properties too. So if i enter some data then press the generate random button i'd expect the properties i have already set to keep their values too not just optional ones

**Comment by bestbeforetoday** [comment]
Note that this issue is not intended to change the behaviour of random data generation; just the behaviour of ticking and un-ticking the _Optional properties_ checkbox. See the discussion in #1816

**Comment by caroline-church** [comment]
I know but it is related and he has already fixed other properties when
generating random data just not for optional properties.

**Pull request merged**
